repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-ast
    -   id: check-added-large-files
    -   id: check-json
    -   id: detect-private-key

-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8

- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.2.3
  hooks:
   - id: nbqa-isort
     additional_dependencies: [isort==5.10.1]
   - id: nbqa-flake8
     additional_dependencies: [flake8==4.0.1]
